name: LastChat
description: Chatting App like WhatsApp made with Flutter SDK
version: 2.0.0+1
author: Shivam Goyal
homepage: https://shivamgoyal.co
repository: https://github.com/ShivamGoyal1899/LastChat

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera:
  fluro:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
