name: WhatsApp
description: WhatsApp UI Clone
version: 3.5.1+1
author: Shivam Goyal
homepage: https://shivamgoyal.co
repository: https://github.com/ShivamGoyal1899/WhatsAppClone

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera: ^0.5.2+2
  story_view : ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
